kind: Deployment
apiVersion: apps/v1
metadata:
  name: backend-chatapp-deployment
  namespace: chatapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      name: backend-pod
      namespace: chatapp
      labels:
        app: backend
    spec:
      containers: 
      - name: chatapp-backend
        image: mpdhanveer05/fullstack-chat-app-backend:latest
        ports:
        - containerPort: 5001
        env:
        - name: NODE_ENV
          value: production
        - name: MONGODB_URI
          value: "mongodb://mongoadmin:root@mongodb:27017/dbname?authSource=admin"  
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: chatapp-secrets
              key: jwt
        - name: PORT
          value: "5001" 
