apiVersion: v1
kind: Secret
metadata:
  name: chatapp-secrets
  namespace: chatapp
type: Opaque
data:
  jwt: ZXlKaGJHY2lPaUpJVXpJMU5pSjkuZXlKU2IyeGxJam9pUVdSdGFXNGlMQ0pKYzNOMVpYSWlPaUpKYzNOMVpYSWlMQ0pWYzJWeWJtRnRaU0k2SWtwaGRtRkpibFZ6WlNJc0ltVjRjQ0k2TVRjME1qQTJNak0wTlN3aWFXRjBJam94TnpReU1EWXlNelExZlEubDVCeFhnUFFvbk91SWJPNUd3T3pCNjRub2ZQakVIWnNSN0FVTE5rNlBIaw==

